DATASET DUZENLEME

In [1]:
import pandas as pd

Coronavirüs hastalığı (COVID-19), yeni keşfedilen bir koronavirüsün neden olduğu bulaşıcı bir hastalıktır. COVİD-19 virüsüyle enfekte olan kişilerin çoğu, hafif ila orta şiddette solunum yolu hastalığı yaşayacak ve özel bir tedavi gerektirmeden iyileşecektir. Yaşlı insanların ve kardiyovasküler hastalık, diyabet, kronik solunum yolu hastalığı ve kanser gibi altta yatan tıbbi sorunları olanların ciddi hastalıklara yakalanma olasılığı daha yüksektir.
Pandemi süreci boyunca sağlık hizmeti sağlayıcılarının karşılaştığı temel sorunlardan biri tıbbi kaynak sıkıntısı ve bu kaynakların verimli bir şekilde dağıtılması için uygun bir planın olmamasıydı. Bu zor zamanlarda, bir kişinin testi pozitif çıktığı anda veya bundan önce ne tür bir kaynağa ihtiyaç duyabileceğini tahmin edebilmek, yetkililere, gerekli kaynakları temin edip ayarlayabilecekleri için çok büyük fayda sağlayacaktır.

Bu projenin ana hedefi, bir Kovid-19 hastasının mevcut semptomu, durumu ve tıbbi geçmişi göz önüne alındığında, hastanın yüksek risk altında olup olmadığını tahmin edecek bir makine öğrenimi modeli oluşturmaktır.
Veri seti Meksika hükümeti tarafından sağlandı  . Bu veri seti, ön koşullar da dahil olmak üzere hastayla ilgili çok sayıda anonimleştirilmiş bilgi içerir. Ham veri seti 21 benzersiz özellik ve 1.048.576 benzersiz hastadan oluşmaktadır. Boolean özelliklerinde 1 "evet", 2 "hayır" anlamına gelir. 97 ve 99 gibi değerler eksik veridir .
Veri setini bu zamana kadar 36.8K kişi indirmiştir
Veri seti en son 1 yıl önce güncellenmiştir.

* sex: Kadın için 1, erkek için 2.
* age: hastanın yaşı.
* classification: covid test bulguları. 1-3 arası değerler hastaya farklı derecelerde covid tanısı konduğu anlamına gelir.
4 veya daha yüksek olması, hastanın covid taşıyıcısı olmadığı veya testin sonuçsuz kaldığı anlamına gelir.
* patient type: Hastanın ünitede aldığı bakımın türü. 1'i eve dönüş ve 2'si hastaneye kaldırılma için.
* pneumonia: Hastanın halihazırda hava keselerinde iltihaplanma olup olmadığı.
* pregnancy: Hastanın hamile olup olmadığı.
* diabetes: hastanın diyabet hastası olup olmadığı.
* copd: Hastanın Kronik obstrüktif akciğer hastalığı olup olmadığını belirtir.
* asthma: hastanın astımı olup olmadığı.
* inmsupr: hastanın immün sistemi baskılanmış olup olmadığı.
* hypertension: hastanın hipertansiyonu olup olmadığı.
* cardiovascular: hastanın kalp veya kan damarlarıyla ilgili hastalığı olup olmadığı.
* renal chronic: hastanın kronik böbrek hastalığı olup olmadığı.
* other disease: hastanın başka bir hastalığı olup olmadığı.
* obesity: hastanın obez olup olmadığı.
* tobacco: hastanın tütün kullanıcısı olup olmadığı.
* usmr: Hastanın birinci, ikinci veya üçüncü düzey tıbbi birimlerde tedavi görüp görmediğini belirtir.
* medical : Ulusal Sağlık Sisteminin bakımı sağlayan kurum türü.
* intubed: hastanın ventilatöre bağlı olup olmadığı.
* icu: Hastanın Yoğun Bakım Ünitesine alınıp alınmadığını gösterir.
* date died: Hasta öldüyse ölüm tarihini belirtin, aksi takdirde 9999-99-99'u belirtin.

In [2]:
# reading csv files
data =  pd.read_csv('Covid Data.csv', sep=",")
df = data.copy() #her ihtimale karşı yedekleyelim
df.head()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97

In [3]:
df.shape

(1048575, 21)

In [4]:
df.info() 
#kaba bir şekide veri setinin tüm yapısal bilgilerini verir.
#bir pandas dataframe şeklindeymiş
#1048575  adet gözlem değerimiz varmış
# 21  değişkenimiz varmış, değişkenlerin tipleri belirtilmiş
#Ramda 168.0+ MB alan tutmuş

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   USMER                 1048575 non-null  int64
 1   MEDICAL_UNIT          1048575 non-null  int64
 2   SEX                   1048575 non-null  int64
 3   PATIENT_TYPE          1048575 non-null  int64
 4   DATE_DIED             1048575 non-null  object
 5   INTUBED               1048575 non-null  int64
 6   PNEUMONIA             1048575 non-null  int64
 7   AGE                   1048575 non-null  int64
 8   PREGNANT              1048575 non-null  int64
 9   DIABETES              1048575 non-null  int64
 10  COPD                  1048575 non-null  int64
 11  ASTHMA                1048575 non-null  int64
 12  INMSUPR               1048575 non-null  int64
 13  HIPERTENSION          1048575 non-null  int64
 14  OTHER_DISEASE         1048575 non-null  int64
 15  CARDIOVASCULAR        1048575 non-null  int64
 16  OBESITY               1048575 non-null  int64
 17  RENAL_CHRONIC         1048575 non-null  int64
 18  TOBACCO               1048575 non-null  int64
 19  CLASIFFICATION_FINAL  1048575 non-null  int64
 20  ICU                   1048575 non-null  int64
dtypes: int64(20), object(1)
memory usage: 168.0+ MB

In [5]:
df.columns = ["TedaviDurumu","TibbiBirim","Cinsiyet","HastaTuru","SaglikDurumu","Entube","Zaturre","Yas","Hamile","Diyabet",
             "KOAH","Astim","BagisiklikSistemi","HiperTansiyon","DigerHastalik","Kardiyovaskuler","Obezite","KronikBobrek",
             "Sigara","CovidSiniflandirma","ICU"] 
#değişken isimlerini değiştiriyoruz

In [6]:
df.info() 
#kaba bir şekide veri setinin tüm yapısal bilgilerini verir.
#bir pandas dataframe şeklindeymiş
#53940 adet gözlem değerimiz varmış
# 10 değişkenimiz varmış, değişkenlerin tipleri belirtilmiş
#Ramda 3MB alan tutmuş

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   TedaviDurumu        1048575 non-null  int64
 1   TibbiBirim          1048575 non-null  int64
 2   Cinsiyet            1048575 non-null  int64
 3   HastaTuru           1048575 non-null  int64
 4   SaglikDurumu        1048575 non-null  object
 5   Entube              1048575 non-null  int64
 6   Zaturre             1048575 non-null  int64
 7   Yas                 1048575 non-null  int64
 8   Hamile              1048575 non-null  int64
 9   Diyabet             1048575 non-null  int64
 10  KOAH                1048575 non-null  int64
 11  Astim               1048575 non-null  int64
 12  BagisiklikSistemi   1048575 non-null  int64
 13  HiperTansiyon       1048575 non-null  int64
 14  DigerHastalik       1048575 non-null  int64
 15  Kardiyovaskuler     1048575 non-null  int64
 16  Obezite             1048575 non-null  int64
 17  KronikBobrek        1048575 non-null  int64
 18  Sigara              1048575 non-null  int64
 19  CovidSiniflandirma  1048575 non-null  int64
 20  ICU                 1048575 non-null  int64
dtypes: int64(20), object(1)
memory usage: 168.0+ MB

In [7]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,2,2,9999-99-99,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,2,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,2,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [8]:
# 'cinsiyet' sütunundaki değerleri değiştir
df['Cinsiyet'] = df['Cinsiyet'].map({1: 'Kadın', 2: 'Erkek'})

In [9]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,Erkek,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,Erkek,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,Erkek,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,Erkek,2,9999-99-99,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,Erkek,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,Erkek,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [10]:
# Cinsiyeti 1 olanları kadın yap, değilse erkek yap
df.loc[df['SaglikDurumu'] != '9999-99-99', 'SaglikDurumu'] = 'Ölü'
df.loc[df['SaglikDurumu'] == '9999-99-99', 'SaglikDurumu'] = 'Sağ'

In [11]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,Ölü,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,Erkek,1,Ölü,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,Erkek,2,Ölü,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,Ölü,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,Erkek,1,Ölü,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,Sağ,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,Erkek,2,Sağ,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,Sağ,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,Erkek,1,Sağ,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,Erkek,1,Sağ,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [12]:
# df['Entube'] = df['Entube'].astype(str)  #Null yapmak için ilk önce değişken türünü null yapıyorum
# df['TedaviDurumu'] = df['TedaviDurumu'].astype(str) 
# df['TibbiBirim'] = df['TibbiBirim'].astype(str) 
# df['Cinsiyet'] = df['Cinsiyet'].astype(str) 
# df['HastaTuru'] = df['HastaTuru'].astype(str) 
# df['SaglikDurumu'] = df['SaglikDurumu'].astype(str)
# df['Zaturre'] = df['Zaturre'].astype(str) 
# df['Yas'] = df['Yas'].astype(str) 
# df['Hamile'] = df['Hamile'].astype(str) 

# df['KOAH'] = df['KOAH'].astype(str) 
# df['Astim'] = df['Astim'].astype(str) 
# df['BagisiklikSistemi'] = df['BagisiklikSistemi'].astype(str) 
# df['HiperTansiyon'] = df['HiperTansiyon'].astype(str)
# df['DigerHastalik'] = df['DigerHastalik'].astype(str) 
# df['Kardiyovaskuler'] = df['Kardiyovaskuler'].astype(str) 
# df['Obezite'] = df['Obezite'].astype(str) 

# df['KronikBobrek'] = df['KronikBobrek'].astype(str) 
# df['Sigara'] = df['Sigara'].astype(str) 
# df['CovidSiniflandirma'] = df['CovidSiniflandirma'].astype(str) 
# df['ICU'] = df['ICU'].astype(str)

In [13]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,Ölü,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,Erkek,1,Ölü,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,Erkek,2,Ölü,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,Ölü,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,Erkek,1,Ölü,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,Sağ,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,Erkek,2,Sağ,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,Sağ,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,Erkek,1,Sağ,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,Erkek,1,Sağ,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [14]:
# Özel bir dönüşüm fonksiyonu tanımla
def safe_convert_to_str(value):
    if (value == 97 or value == 99):
        return pd.NA;
    else:
        return str(value);

# applymap fonksiyonunu kullanarak tüm DataFrame'i dönüştür
df = df.applymap(safe_convert_to_str)

In [15]:
# df.loc[df['TedaviDurumu'] == '99', 'TedaviDurumu'] = None 
# df.loc[df['TedaviDurumu'] == '97', 'TedaviDurumu'] = None 
# df.loc[df['TibbiBirim'] == '99', 'TibbiBirim'] = None 
# df.loc[df['TibbiBirim'] == '97', 'TibbiBirim'] = None 
# df.loc[df['Cinsiyet'] == '99', 'Cinsiyet'] = None 
# df.loc[df['Cinsiyet'] == '97', 'Cinsiyet'] = None 
# df.loc[df['HastaTuru'] == '99', 'HastaTuru'] = None 
# df.loc[df['HastaTuru'] == '97', 'HastaTuru'] = None 
# df.loc[df['SaglikDurumu'] == '99', 'SaglikDurumu'] = None 
# df.loc[df['SaglikDurumu'] == '97', 'SaglikDurumu'] = None 
# df.loc[df['Entube'] == '99', 'Entube'] = None 
# df.loc[df['Entube'] == '97', 'Entube'] = None 
# df.loc[df['Zaturre'] == '99', 'Zaturre'] = None 
# df.loc[df['Zaturre'] == '97', 'Zaturre'] = None 
# df.loc[df['Yas'] == '99', 'Yas'] = None 
# df.loc[df['Yas'] == '97', 'Yas'] = None 
# df.loc[df['Hamile'] == '99', 'Hamile'] = None 
# df.loc[df['Hamile'] == '97', 'Hamile'] = None 
# df.loc[df['Diyabet'] == '99', 'Diyabet'] = None 
# df.loc[df['Diyabet'] == '97', 'Diyabet'] = None 
# df.loc[df['KOAH'] == '99', 'KOAH'] = None 
# df.loc[df['KOAH'] == '97', 'KOAH'] = None 
# df.loc[df['Astim'] == '99', 'Astim'] = None 
# df.loc[df['Astim'] == '97', 'Astim'] = None 
# df.loc[df['BagisiklikSistemi'] == '99', 'BagisiklikSistemi'] = None 
# df.loc[df['BagisiklikSistemi'] == '97', 'BagisiklikSistemi'] = None 
# df.loc[df['HiperTansiyon'] == '99', 'HiperTansiyon'] = None 
# df.loc[df['HiperTansiyon'] == '97', 'HiperTansiyon'] = None 
# df.loc[df['DigerHastalik'] == '99', 'DigerHastalik'] = None 
# df.loc[df['DigerHastalik'] == '97', 'DigerHastalik'] = None 
# df.loc[df['Kardiyovaskuler'] == '99', 'Kardiyovaskuler'] = None 
# df.loc[df['Kardiyovaskuler'] == '97', 'Kardiyovaskuler'] = None 
# df.loc[df['Obezite'] == '99', 'Obezite'] = None 
# df.loc[df['Obezite'] == '97', 'Obezite'] = None 
# df.loc[df['KronikBobrek'] == '99', 'KronikBobrek'] = None 
# df.loc[df['KronikBobrek'] == '97', 'KronikBobrek'] = None 
# df.loc[df['Sigara'] == '99', 'Sigara'] = None 
# df.loc[df['Sigara'] == '97', 'Sigara'] = None 
# df.loc[df['CovidSiniflandirma'] == '99', 'CovidSiniflandirma'] = None 
# df.loc[df['CovidSiniflandirma'] == '97', 'CovidSiniflandirma'] = None
# df.loc[df['ICU'] == '99', 'ICU'] = None 
# df.loc[df['ICU'] == '97', 'ICU'] = None

In [16]:
# # 'None' olan değerleri 'NaN' ile değiştir
# df.replace(to_replace=[None], value=pd.NA, inplace=True)

In [17]:
#hiç eksik gözlem(değer) var mı
df.isnull().values.any() # isnull() values üzerinde bir sorgulama yap herhangi birisinde (any) eksik değer varsa true olarak dön.

True

In [18]:
df.isnull().sum() #tüm değişkenlerdeki toplam eksik değer sayısını verir. Hangi değişkende ne kadar eksik var sorusuna cevap alırız.

TedaviDurumu               0
TibbiBirim                 0
Cinsiyet                   0
HastaTuru                  0
SaglikDurumu               0
Entube                855869
Zaturre                16003
Yas                      221
Hamile                523511
Diyabet                    0
KOAH                       0
Astim                      0
BagisiklikSistemi          0
HiperTansiyon              0
DigerHastalik              0
Kardiyovaskuler            0
Obezite                    0
KronikBobrek               0
Sigara                     0
CovidSiniflandirma         0
ICU                   856032
dtype: int64

In [19]:
# df['Entube'] = df['Entube'].astype(str)  #Null yapmak için ilk önce değişken türünü null yapıyorum
# df['TedaviDurumu'] = df['TedaviDurumu'].astype(str) 
# df['TibbiBirim'] = df['TibbiBirim'].astype(str) 
# df['Cinsiyet'] = df['Cinsiyet'].astype(str) 
# df['HastaTuru'] = df['HastaTuru'].astype(str) 
# df['SaglikDurumu'] = df['SaglikDurumu'].astype(str)
# df['Zaturre'] = df['Zaturre'].astype(str) 
# df['Yas'] = df['Yas'].astype(str) 
# df['Hamile'] = df['Hamile'].astype(str)
# df['Diyabet'] = df['Diyabet'].astype(str) 

# df['KOAH'] = df['KOAH'].astype(str) 
# df['Astim'] = df['Astim'].astype(str) 
# df['BagisiklikSistemi'] = df['BagisiklikSistemi'].astype(str) 
# df['HiperTansiyon'] = df['HiperTansiyon'].astype(str)
# df['DigerHastalik'] = df['DigerHastalik'].astype(str) 
# df['Kardiyovaskuler'] = df['Kardiyovaskuler'].astype(str) 
# df['Obezite'] = df['Obezite'].astype(str) 

# df['KronikBobrek'] = df['KronikBobrek'].astype(str) 
# df['Sigara'] = df['Sigara'].astype(str) 
# df['CovidSiniflandirma'] = df['CovidSiniflandirma'].astype(str) 
# df['ICU'] = df['ICU'].astype(str)

In [20]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,Ölü,<NA>,1,65,2,2,...,2,2,1,2,2,2,2,2,3,<NA>
1,2,1,Erkek,1,Ölü,<NA>,1,72,<NA>,2,...,2,2,1,2,2,1,1,2,5,<NA>
2,2,1,Erkek,2,Ölü,1,2,55,<NA>,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,Ölü,<NA>,2,53,2,2,...,2,2,2,2,2,2,2,2,7,<NA>
4,2,1,Erkek,1,Ölü,<NA>,2,68,<NA>,1,...,2,2,1,2,2,2,2,2,3,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,Sağ,<NA>,2,40,<NA>,2,...,2,2,2,2,2,2,2,2,7,<NA>
1048571,1,13,Erkek,2,Sağ,2,2,51,<NA>,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,Sağ,<NA>,2,55,<NA>,2,...,2,2,2,2,2,2,2,2,7,<NA>
1048573,2,13,Erkek,1,Sağ,<NA>,2,28,<NA>,2,...,2,2,2,2,2,2,2,2,7,<NA>
1048574,2,13,Erkek,1,Sağ,<NA>,2,52,<NA>,2,...,2,2,2,2,2,2,2,2,7,<NA>

In [21]:
df.info() 
#kaba bir şekide veri setinin tüm yapısal bilgilerini verir.
#bir pandas dataframe şeklindeymiş
#53940 adet gözlem değerimiz varmış
# 10 değişkenimiz varmış, değişkenlerin tipleri belirtilmiş
#Ramda 3MB alan tutmuş

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   TedaviDurumu        1048575 non-null  object
 1   TibbiBirim          1048575 non-null  object
 2   Cinsiyet            1048575 non-null  object
 3   HastaTuru           1048575 non-null  object
 4   SaglikDurumu        1048575 non-null  object
 5   Entube              192706 non-null   object
 6   Zaturre             1032572 non-null  object
 7   Yas                 1048354 non-null  object
 8   Hamile              525064 non-null   object
 9   Diyabet             1048575 non-null  object
 10  KOAH                1048575 non-null  object
 11  Astim               1048575 non-null  object
 12  BagisiklikSistemi   1048575 non-null  object
 13  HiperTansiyon       1048575 non-null  object
 14  DigerHastalik       1048575 non-null  object
 15  Kardiyovaskuler     1048575 non-null  object
 16  Obezite             1048575 non-null  object
 17  KronikBobrek        1048575 non-null  object
 18  Sigara              1048575 non-null  object
 19  CovidSiniflandirma  1048575 non-null  object
 20  ICU                 192543 non-null   object
dtypes: object(21)
memory usage: 168.0+ MB

In [22]:
# df['HastaTuru'] = df['HastaTuru'].pd.to_numeric(df['HastaTuru'], errors='coerce').astype('Int64')
# df['Yas'] = df['Yas'].pd.to_numeric(df['Yas'], errors='coerce').astype('Int64')
# df['CovidSiniflandirma'] = df['CovidSiniflandirma'].pd.to_numeric(df['CovidSiniflandirma'], errors='coerce').astype('Int64')


# 'Yas' sütununu string'ten int'e çevir
df['Yas'] = pd.to_numeric(df['Yas'], errors='coerce').astype('Int64')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   TedaviDurumu        1048575 non-null  object
 1   TibbiBirim          1048575 non-null  object
 2   Cinsiyet            1048575 non-null  object
 3   HastaTuru           1048575 non-null  object
 4   SaglikDurumu        1048575 non-null  object
 5   Entube              192706 non-null   object
 6   Zaturre             1032572 non-null  object
 7   Yas                 1048354 non-null  Int64
 8   Hamile              525064 non-null   object
 9   Diyabet             1048575 non-null  object
 10  KOAH                1048575 non-null  object
 11  Astim               1048575 non-null  object
 12  BagisiklikSistemi   1048575 non-null  object
 13  HiperTansiyon       1048575 non-null  object
 14  DigerHastalik       1048575 non-null  object
 15  Kardiyovaskuler     1048575 non-null  object
 16  Obezite             1048575 non-null  object
 17  KronikBobrek        1048575 non-null  object
 18  Sigara              1048575 non-null  object
 19  CovidSiniflandirma  1048575 non-null  object
 20  ICU                 192543 non-null   object
dtypes: Int64(1), object(20)
memory usage: 169.0+ MB

In [24]:
df.isnull().sum() #tüm değişkenlerdeki toplam eksik değer sayısını verir. Hangi değişkende ne kadar eksik var sorusuna cevap alırız.

TedaviDurumu               0
TibbiBirim                 0
Cinsiyet                   0
HastaTuru                  0
SaglikDurumu               0
Entube                855869
Zaturre                16003
Yas                      221
Hamile                523511
Diyabet                    0
KOAH                       0
Astim                      0
BagisiklikSistemi          0
HiperTansiyon              0
DigerHastalik              0
Kardiyovaskuler            0
Obezite                    0
KronikBobrek               0
Sigara                     0
CovidSiniflandirma         0
ICU                   856032
dtype: int64

In [25]:
# DataFrame'i CSV dosyasına kaydet
df.to_csv('duzenlenmis_Covid19.csv', index=False)

In [26]:
import pandas as pd

Coronavirüs hastalığı (COVID-19), yeni keşfedilen bir koronavirüsün neden olduğu bulaşıcı bir hastalıktır. COVİD-19 virüsüyle enfekte olan kişilerin çoğu, hafif ila orta şiddette solunum yolu hastalığı yaşayacak ve özel bir tedavi gerektirmeden iyileşecektir. Yaşlı insanların ve kardiyovasküler hastalık, diyabet, kronik solunum yolu hastalığı ve kanser gibi altta yatan tıbbi sorunları olanların ciddi hastalıklara yakalanma olasılığı daha yüksektir.
Pandemi süreci boyunca sağlık hizmeti sağlayıcılarının karşılaştığı temel sorunlardan biri tıbbi kaynak sıkıntısı ve bu kaynakların verimli bir şekilde dağıtılması için uygun bir planın olmamasıydı. Bu zor zamanlarda, bir kişinin testi pozitif çıktığı anda veya bundan önce ne tür bir kaynağa ihtiyaç duyabileceğini tahmin edebilmek, yetkililere, gerekli kaynakları temin edip ayarlayabilecekleri için çok büyük fayda sağlayacaktır.

Bu projenin ana hedefi, bir Kovid-19 hastasının mevcut semptomu, durumu ve tıbbi geçmişi göz önüne alındığında, hastanın yüksek risk altında olup olmadığını tahmin edecek bir makine öğrenimi modeli oluşturmaktır.
Veri seti Meksika hükümeti tarafından sağlandı  . Bu veri seti, ön koşullar da dahil olmak üzere hastayla ilgili çok sayıda anonimleştirilmiş bilgi içerir. Ham veri seti 21 benzersiz özellik ve 1.048.576 benzersiz hastadan oluşmaktadır. Boolean özelliklerinde 1 "evet", 2 "hayır" anlamına gelir. 
Veri setini bu zamana kadar 36.8K kişi indirmiştir
Veri seti en son 1 yıl önce güncellenmiştir.

* Cinsiyet: Kadın ve erkek değerlerin oluşmaktadır.
* Yaş: hastanın yaşı.
* sınıflandırma: covid test bulguları. 1-3 arası değerler hastaya farklı derecelerde covid tanısı konduğu anlamına gelir
. 4 veya daha yüksek olması, hastanın covid taşıyıcısı olmadığı veya testin sonuçsuz kaldığı anlamına gelir.
* Hasta türü: Hastanın ünitede aldığı bakımın türü. 1'i eve dönüş ve 2'si hastaneye kaldırılma için.
* pnömoni: Hastanın halihazırda hava keselerinde iltihaplanma olup olmadığı.
* Hamilelik: Hastanın hamile olup olmadığı.
* diyabet: hastanın diyabet hastası olup olmadığı.
* KOAH: Hastanın Kronik obstrüktif akciğer hastalığı olup olmadığını belirtir.
* astım: hastanın astımı olup olmadığı.
* inmsupr: hastanın bağışıklılık sistemi baskılanmış olup olmadığı.
* hipertansiyon: hastanın hipertansiyonu olup olmadığı.
* kardiyovasküler: hastanın kalp veya kan damarlarıyla ilgili hastalığı olup olmadığı.
* kronik böbrek: hastanın kronik böbrek hastalığı olup olmadığı.
* diğer hastalık: hastanın başka bir hastalığı olup olmadığı.
* obezite: hastanın obez olup olmadığı.
* tütün: hastanın tütün kullanıcısı olup olmadığı.
* usmr: Hastanın birinci, ikinci veya üçüncü düzey tıbbi birimlerde tedavi görüp görmediğini belirtir.
* tıbbi birim: Ulusal Sağlık Sisteminin bakımı sağlayan kurum türü.
* entübe: hastanın ventilatöre bağlı olup olmadığı.
* icu: Hastanın Yoğun Bakım Ünitesine alınıp alınmadığını gösterir.
* ölüm tarihi: Hasta öldüyse ölüm tarihini belirtin, aksi takdirde 9999-99-99'u belirtin.

In [27]:
# reading csv files
data =  pd.read_csv('duzenlenmis_Covid19.csv', sep=",")
df = data.copy() #her ihtimale karşı yedekleyelim
df.head()

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,Ölü,NaN,1.0,65.0,2.0,2,...,2,2,1,2,2,2,2,2,3,NaN
1,2,1,Erkek,1,Ölü,NaN,1.0,72.0,NaN,2,...,2,2,1,2,2,1,1,2,5,NaN
2,2,1,Erkek,2,Ölü,1.0,2.0,55.0,NaN,1,...,2,2,2,2,2,2,2,2,3,2.0
3,2,1,Kadın,1,Ölü,NaN,2.0,53.0,2.0,2,...,2,2,2,2,2,2,2,2,7,NaN
4,2,1,Erkek,1,Ölü,NaN,2.0,68.0,NaN,1,...,2,2,1,2,2,2,2,2,3,NaN

In [28]:
# 'Entube' sütununu float'tan int'e çevir
df['Yas'] = pd.to_numeric(df['Yas'], errors='coerce').astype('Int64')
df['Hamile'] = pd.to_numeric(df['Hamile'], errors='coerce').astype('Int64')
df['Zaturre'] = pd.to_numeric(df['Zaturre'], errors='coerce').astype('Int64')
df['Entube'] = pd.to_numeric(df['Entube'], errors='coerce').astype('Int64')
df['ICU'] = pd.to_numeric(df['ICU'], errors='coerce').astype('Int64')

#Pandas kütüphanesi null değişken algıladığında float olarak algılar.
#Float Değişkeni NaN değerini en iyi temsil eden veri tipidir. Bu yüzden float algılar.


# Tüm float sütunlarını int'e dönüştür (NaN değerleri korunur)
# df = df.applymap(pd.to_numeric(df['Diyabet'], errors='coerce').astype('Int64')

In [29]:
# Özel bir dönüşüm fonksiyonu tanımla
def safe_convert_to_str2(value):
    if (pd.isnull(value)):
        return pd.NA;
    else:
        return str(value);

# applymap fonksiyonunu kullanarak tüm DataFrame'i dönüştür
df = df.applymap(safe_convert_to_str2)

In [30]:
# 'Yas' sütununu string'ten int'e çevir
df['Yas'] = pd.to_numeric(df['Yas'], errors='coerce').astype('Int64')

In [31]:
# df['Entube'] = df['Entube'].astype(str)  #Null yapmak için ilk önce değişken türünü null yapıyorum
# df['TedaviDurumu'] = df['TedaviDurumu'].astype(str) 
# df['TibbiBirim'] = df['TibbiBirim'].astype(str) 
# df['Cinsiyet'] = df['Cinsiyet'].astype(str) 
# df['HastaTuru'] = df['HastaTuru'].astype(str) 
# df['SaglikDurumu'] = df['SaglikDurumu'].astype(str)
# df['Zaturre'] = df['Zaturre'].astype(str) 
# df['Hamile'] = df['Hamile'].astype(str)
# df['Diyabet'] = df['Diyabet'].astype(str) 

# df['KOAH'] = df['KOAH'].astype(str) 
# df['Astim'] = df['Astim'].astype(str) 
# df['BagisiklikSistemi'] = df['BagisiklikSistemi'].astype(str) 
# df['HiperTansiyon'] = df['HiperTansiyon'].astype(str)
# df['DigerHastalik'] = df['DigerHastalik'].astype(str) 
# df['Kardiyovaskuler'] = df['Kardiyovaskuler'].astype(str) 
# df['Obezite'] = df['Obezite'].astype(str) 

# df['KronikBobrek'] = df['KronikBobrek'].astype(str) 
# df['Sigara'] = df['Sigara'].astype(str) 
# df['CovidSiniflandirma'] = df['CovidSiniflandirma'].astype(str) 
# df['ICU'] = df['ICU'].astype(str)

# # 'Yas' sütununu string'ten int'e çevir
# df['Yas'] = pd.to_numeric(df['Yas'], errors='coerce').astype('Int64')

In [32]:
# # int değişkenleri stringe dönüştür (None'ları 'NaN' ile değiştir)
# df['Entube'] = df['Entube'].astype(str)
# df['Zaturre'] = df['Zaturre'].astype(str)
# df['Hamile'] = df['Hamile'].astype(str)
# df['ICU'] = df['ICU'].astype(str)

# # 'None' olan değerleri 'NaN' ile değiştir
# df.replace(to_replace='None', value='NaN', inplace=True)

In [33]:
df.shape

(1048575, 21)

In [34]:
df.info() 
#kaba bir şekide veri setinin tüm yapısal bilgilerini verir.
#bir pandas dataframe şeklindeymiş
#1048575 adet gözlem değerimiz varmış
# 21 değişkenimiz varmış, değişkenlerin tipleri belirtilmiş
#Ramda 168.0+ MB alan tutmuş

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   TedaviDurumu        1048575 non-null  object
 1   TibbiBirim          1048575 non-null  object
 2   Cinsiyet            1048575 non-null  object
 3   HastaTuru           1048575 non-null  object
 4   SaglikDurumu        1048575 non-null  object
 5   Entube              192706 non-null   object
 6   Zaturre             1032572 non-null  object
 7   Yas                 1048354 non-null  Int64
 8   Hamile              525064 non-null   object
 9   Diyabet             1048575 non-null  object
 10  KOAH                1048575 non-null  object
 11  Astim               1048575 non-null  object
 12  BagisiklikSistemi   1048575 non-null  object
 13  HiperTansiyon       1048575 non-null  object
 14  DigerHastalik       1048575 non-null  object
 15  Kardiyovaskuler     1048575 non-null  object
 16  Obezite             1048575 non-null  object
 17  KronikBobrek        1048575 non-null  object
 18  Sigara              1048575 non-null  object
 19  CovidSiniflandirma  1048575 non-null  object
 20  ICU                 192543 non-null   object
dtypes: Int64(1), object(20)
memory usage: 169.0+ MB

In [35]:
df.describe() #sürekli (sayısal) değişkenlerin betimsel özelliklerine bakalım

             Yas
count  1048354.0
mean   41.782301
std    16.889613
min          0.0
25%         30.0
50%         40.0
75%         53.0
max        121.0

In [36]:
#hiç eksik gözlem(değer) var mı
df.isnull().values.any() # isnull() values üzerinde bir sorgulama yap herhangi birisinde (any) eksik değer varsa true olarak dön.

True

In [37]:
df.isnull().sum() #tüm değişkenlerdeki toplam eksik değer sayısını verir. Hangi değişkende ne kadar eksik var sorusuna cevap alırız.

TedaviDurumu               0
TibbiBirim                 0
Cinsiyet                   0
HastaTuru                  0
SaglikDurumu               0
Entube                855869
Zaturre                16003
Yas                      221
Hamile                523511
Diyabet                    0
KOAH                       0
Astim                      0
BagisiklikSistemi          0
HiperTansiyon              0
DigerHastalik              0
Kardiyovaskuler            0
Obezite                    0
KronikBobrek               0
Sigara                     0
CovidSiniflandirma         0
ICU                   856032
dtype: int64

In [38]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,Ölü,<NA>,1,65,2,2,...,2,2,1,2,2,2,2,2,3,<NA>
1,2,1,Erkek,1,Ölü,<NA>,1,72,<NA>,2,...,2,2,1,2,2,1,1,2,5,<NA>
2,2,1,Erkek,2,Ölü,1,2,55,<NA>,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,Ölü,<NA>,2,53,2,2,...,2,2,2,2,2,2,2,2,7,<NA>
4,2,1,Erkek,1,Ölü,<NA>,2,68,<NA>,1,...,2,2,1,2,2,2,2,2,3,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,Sağ,<NA>,2,40,<NA>,2,...,2,2,2,2,2,2,2,2,7,<NA>
1048571,1,13,Erkek,2,Sağ,2,2,51,<NA>,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,Sağ,<NA>,2,55,<NA>,2,...,2,2,2,2,2,2,2,2,7,<NA>
1048573,2,13,Erkek,1,Sağ,<NA>,2,28,<NA>,2,...,2,2,2,2,2,2,2,2,7,<NA>
1048574,2,13,Erkek,1,Sağ,<NA>,2,52,<NA>,2,...,2,2,2,2,2,2,2,2,7,<NA>