DATASET DUZENLEME

In [38]:
import pandas as pd

In [39]:
# reading csv files
data =  pd.read_csv('Covid Data.csv', sep=",")
df = data.copy() #her ihtimale karşı yedekleyelim
df.head()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97

In [40]:
df.shape

(1048575, 21)

In [41]:
df.info() 
#kaba bir şekide veri setinin tüm yapısal bilgilerini verir.
#bir pandas dataframe şeklindeymiş
#53940 adet gözlem değerimiz varmış
# 10 değişkenimiz varmış, değişkenlerin tipleri belirtilmiş
#Ramda 3MB alan tutmuş

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   USMER                 1048575 non-null  int64
 1   MEDICAL_UNIT          1048575 non-null  int64
 2   SEX                   1048575 non-null  int64
 3   PATIENT_TYPE          1048575 non-null  int64
 4   DATE_DIED             1048575 non-null  object
 5   INTUBED               1048575 non-null  int64
 6   PNEUMONIA             1048575 non-null  int64
 7   AGE                   1048575 non-null  int64
 8   PREGNANT              1048575 non-null  int64
 9   DIABETES              1048575 non-null  int64
 10  COPD                  1048575 non-null  int64
 11  ASTHMA                1048575 non-null  int64
 12  INMSUPR               1048575 non-null  int64
 13  HIPERTENSION          1048575 non-null  int64
 14  OTHER_DISEASE         1048575 non-null  int64
 15  CARDIOVASCULAR        1048575 non-null  int64
 16  OBESITY               1048575 non-null  int64
 17  RENAL_CHRONIC         1048575 non-null  int64
 18  TOBACCO               1048575 non-null  int64
 19  CLASIFFICATION_FINAL  1048575 non-null  int64
 20  ICU                   1048575 non-null  int64
dtypes: int64(20), object(1)
memory usage: 168.0+ MB

In [42]:
df.columns = ["TedaviDurumu","TibbiBirim","Cinsiyet","HastaTuru","SaglikDurumu","Entube","Zaturre","Yas","Hamile","Diyabet",
             "KOAH","Astim","BagisiklikSistemi","HiperTansiyon","DigerHastalik","Kardiyovaskuler","Obezite","KronikBobrek",
             "Sigara","CovidSiniflandirma","ICU"] 
#değişken isimlerini değiştiriyoruz

In [43]:
df.info() 
#kaba bir şekide veri setinin tüm yapısal bilgilerini verir.
#bir pandas dataframe şeklindeymiş
#53940 adet gözlem değerimiz varmış
# 10 değişkenimiz varmış, değişkenlerin tipleri belirtilmiş
#Ramda 3MB alan tutmuş

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   TedaviDurumu        1048575 non-null  int64
 1   TibbiBirim          1048575 non-null  int64
 2   Cinsiyet            1048575 non-null  int64
 3   HastaTuru           1048575 non-null  int64
 4   SaglikDurumu        1048575 non-null  object
 5   Entube              1048575 non-null  int64
 6   Zaturre             1048575 non-null  int64
 7   Yas                 1048575 non-null  int64
 8   Hamile              1048575 non-null  int64
 9   Diyabet             1048575 non-null  int64
 10  KOAH                1048575 non-null  int64
 11  Astim               1048575 non-null  int64
 12  BagisiklikSistemi   1048575 non-null  int64
 13  HiperTansiyon       1048575 non-null  int64
 14  DigerHastalik       1048575 non-null  int64
 15  Kardiyovaskuler     1048575 non-null  int64
 16  Obezite             1048575 non-null  int64
 17  KronikBobrek        1048575 non-null  int64
 18  Sigara              1048575 non-null  int64
 19  CovidSiniflandirma  1048575 non-null  int64
 20  ICU                 1048575 non-null  int64
dtypes: int64(20), object(1)
memory usage: 168.0+ MB

In [44]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,2,2,9999-99-99,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,2,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,2,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [45]:
# 'cinsiyet' sütunundaki değerleri değiştir
df['Cinsiyet'] = df['Cinsiyet'].map({1: 'Kadın', 2: 'Erkek'})

In [46]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,Erkek,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,Erkek,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,Erkek,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,Erkek,2,9999-99-99,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,Erkek,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,Erkek,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [47]:
# Cinsiyeti 1 olanları kadın yap, değilse erkek yap
df.loc[df['SaglikDurumu'] != '9999-99-99', 'SaglikDurumu'] = 'Ölü'
df.loc[df['SaglikDurumu'] == '9999-99-99', 'SaglikDurumu'] = 'Sağ'

In [48]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,Ölü,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,Erkek,1,Ölü,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,Erkek,2,Ölü,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,Ölü,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,Erkek,1,Ölü,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,Sağ,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,Erkek,2,Sağ,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,Sağ,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,Erkek,1,Sağ,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,Erkek,1,Sağ,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [49]:
df['Entube'] = df['Entube'].astype(str)  #Null yapmak için ilk önce değişken türünü null yapıyorum
df['TedaviDurumu'] = df['TedaviDurumu'].astype(str) 
df['TibbiBirim'] = df['TibbiBirim'].astype(str) 
df['Cinsiyet'] = df['Cinsiyet'].astype(str) 
df['HastaTuru'] = df['HastaTuru'].astype(str) 
df['SaglikDurumu'] = df['SaglikDurumu'].astype(str)
df['Zaturre'] = df['Zaturre'].astype(str) 
df['Yas'] = df['Yas'].astype(str) 
df['Hamile'] = df['Hamile'].astype(str) 

df['KOAH'] = df['KOAH'].astype(str) 
df['Astim'] = df['Astim'].astype(str) 
df['BagisiklikSistemi'] = df['BagisiklikSistemi'].astype(str) 
df['HiperTansiyon'] = df['HiperTansiyon'].astype(str)
df['DigerHastalik'] = df['DigerHastalik'].astype(str) 
df['Kardiyovaskuler'] = df['Kardiyovaskuler'].astype(str) 
df['Obezite'] = df['Obezite'].astype(str) 

df['KronikBobrek'] = df['KronikBobrek'].astype(str) 
df['Sigara'] = df['Sigara'].astype(str) 
df['CovidSiniflandirma'] = df['CovidSiniflandirma'].astype(str) 
df['ICU'] = df['ICU'].astype(str)

In [50]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,Ölü,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,Erkek,1,Ölü,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,Erkek,2,Ölü,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,Ölü,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,Erkek,1,Ölü,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,Sağ,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,Erkek,2,Sağ,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,Sağ,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,Erkek,1,Sağ,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,Erkek,1,Sağ,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [51]:
df.loc[df['TedaviDurumu'] == '99', 'TedaviDurumu'] = None 
df.loc[df['TedaviDurumu'] == '97', 'TedaviDurumu'] = None 
df.loc[df['TibbiBirim'] == '99', 'TibbiBirim'] = None 
df.loc[df['TibbiBirim'] == '97', 'TibbiBirim'] = None 
df.loc[df['Cinsiyet'] == '99', 'Cinsiyet'] = None 
df.loc[df['Cinsiyet'] == '97', 'Cinsiyet'] = None 
df.loc[df['HastaTuru'] == '99', 'HastaTuru'] = None 
df.loc[df['HastaTuru'] == '97', 'HastaTuru'] = None 
df.loc[df['SaglikDurumu'] == '99', 'SaglikDurumu'] = None 
df.loc[df['SaglikDurumu'] == '97', 'SaglikDurumu'] = None 
df.loc[df['Entube'] == '99', 'Entube'] = None 
df.loc[df['Entube'] == '97', 'Entube'] = None 
df.loc[df['Zaturre'] == '99', 'Zaturre'] = None 
df.loc[df['Zaturre'] == '97', 'Zaturre'] = None 
df.loc[df['Yas'] == '99', 'Yas'] = None 
df.loc[df['Yas'] == '97', 'Yas'] = None 
df.loc[df['Hamile'] == '99', 'Hamile'] = None 
df.loc[df['Hamile'] == '97', 'Hamile'] = None 
df.loc[df['Diyabet'] == '99', 'Diyabet'] = None 
df.loc[df['Diyabet'] == '97', 'Diyabet'] = None 
df.loc[df['KOAH'] == '99', 'KOAH'] = None 
df.loc[df['KOAH'] == '97', 'KOAH'] = None 
df.loc[df['Astim'] == '99', 'Astim'] = None 
df.loc[df['Astim'] == '97', 'Astim'] = None 
df.loc[df['BagisiklikSistemi'] == '99', 'BagisiklikSistemi'] = None 
df.loc[df['BagisiklikSistemi'] == '97', 'BagisiklikSistemi'] = None 
df.loc[df['HiperTansiyon'] == '99', 'HiperTansiyon'] = None 
df.loc[df['HiperTansiyon'] == '97', 'HiperTansiyon'] = None 
df.loc[df['DigerHastalik'] == '99', 'DigerHastalik'] = None 
df.loc[df['DigerHastalik'] == '97', 'DigerHastalik'] = None 
df.loc[df['Kardiyovaskuler'] == '99', 'Kardiyovaskuler'] = None 
df.loc[df['Kardiyovaskuler'] == '97', 'Kardiyovaskuler'] = None 
df.loc[df['Obezite'] == '99', 'Obezite'] = None 
df.loc[df['Obezite'] == '97', 'Obezite'] = None 
df.loc[df['KronikBobrek'] == '99', 'KronikBobrek'] = None 
df.loc[df['KronikBobrek'] == '97', 'KronikBobrek'] = None 
df.loc[df['Sigara'] == '99', 'Sigara'] = None 
df.loc[df['Sigara'] == '97', 'Sigara'] = None 
df.loc[df['CovidSiniflandirma'] == '99', 'CovidSiniflandirma'] = None 
df.loc[df['CovidSiniflandirma'] == '97', 'CovidSiniflandirma'] = None
df.loc[df['ICU'] == '99', 'ICU'] = None 
df.loc[df['ICU'] == '97', 'ICU'] = None

In [52]:
#hiç eksik gözlem(değer) var mı
df.isnull().values.any() # isnull() values üzerinde bir sorgulama yap herhangi birisinde (any) eksik değer varsa true olarak dön.

True

In [53]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,Ölü,None,1,65,2,2.0,...,2,2,1,2,2,2,2,2,3,None
1,2,1,Erkek,1,Ölü,None,1,72,None,2.0,...,2,2,1,2,2,1,1,2,5,None
2,2,1,Erkek,2,Ölü,1,2,55,None,1.0,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,Ölü,None,2,53,2,2.0,...,2,2,2,2,2,2,2,2,7,None
4,2,1,Erkek,1,Ölü,None,2,68,None,1.0,...,2,2,1,2,2,2,2,2,3,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,Sağ,None,2,40,None,2.0,...,2,2,2,2,2,2,2,2,7,None
1048571,1,13,Erkek,2,Sağ,2,2,51,None,2.0,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,Sağ,None,2,55,None,2.0,...,2,2,2,2,2,2,2,2,7,None
1048573,2,13,Erkek,1,Sağ,None,2,28,None,2.0,...,2,2,2,2,2,2,2,2,7,None
1048574,2,13,Erkek,1,Sağ,None,2,52,None,2.0,...,2,2,2,2,2,2,2,2,7,None

In [54]:
# 'Entube' sütununu float'tan int'e çevir
df['Diyabet'] = pd.to_numeric(df['Diyabet'], errors='coerce').astype('Int64')

In [55]:
df

,TedaviDurumu,TibbiBirim,Cinsiyet,HastaTuru,SaglikDurumu,Entube,Zaturre,Yas,Hamile,Diyabet,...,Astim,BagisiklikSistemi,HiperTansiyon,DigerHastalik,Kardiyovaskuler,Obezite,KronikBobrek,Sigara,CovidSiniflandirma,ICU
0,2,1,Kadın,1,Ölü,None,1,65,2,2,...,2,2,1,2,2,2,2,2,3,None
1,2,1,Erkek,1,Ölü,None,1,72,None,2,...,2,2,1,2,2,1,1,2,5,None
2,2,1,Erkek,2,Ölü,1,2,55,None,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,Kadın,1,Ölü,None,2,53,2,2,...,2,2,2,2,2,2,2,2,7,None
4,2,1,Erkek,1,Ölü,None,2,68,None,1,...,2,2,1,2,2,2,2,2,3,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,Erkek,1,Sağ,None,2,40,None,2,...,2,2,2,2,2,2,2,2,7,None
1048571,1,13,Erkek,2,Sağ,2,2,51,None,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,Erkek,1,Sağ,None,2,55,None,2,...,2,2,2,2,2,2,2,2,7,None
1048573,2,13,Erkek,1,Sağ,None,2,28,None,2,...,2,2,2,2,2,2,2,2,7,None
1048574,2,13,Erkek,1,Sağ,None,2,52,None,2,...,2,2,2,2,2,2,2,2,7,None

In [56]:
df['KOAH']

0          2
1          2
2          2
3          2
4          2
          ..
1048570    2
1048571    2
1048572    2
1048573    2
1048574    2
Name: KOAH, Length: 1048575, dtype: object

In [57]:
df.info() 
#kaba bir şekide veri setinin tüm yapısal bilgilerini verir.
#bir pandas dataframe şeklindeymiş
#53940 adet gözlem değerimiz varmış
# 10 değişkenimiz varmış, değişkenlerin tipleri belirtilmiş
#Ramda 3MB alan tutmuş

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   TedaviDurumu        1048575 non-null  object
 1   TibbiBirim          1048575 non-null  object
 2   Cinsiyet            1048575 non-null  object
 3   HastaTuru           1048575 non-null  object
 4   SaglikDurumu        1048575 non-null  object
 5   Entube              192706 non-null   object
 6   Zaturre             1032572 non-null  object
 7   Yas                 1048354 non-null  object
 8   Hamile              525064 non-null   object
 9   Diyabet             1048575 non-null  Int64
 10  KOAH                1048575 non-null  object
 11  Astim               1048575 non-null  object
 12  BagisiklikSistemi   1048575 non-null  object
 13  HiperTansiyon       1048575 non-null  object
 14  DigerHastalik       1048575 non-null  object
 15  Kardiyovaskuler     1048575 non-null  object
 16  Obezite             1048575 non-null  object
 17  KronikBobrek        1048575 non-null  object
 18  Sigara              1048575 non-null  object
 19  CovidSiniflandirma  1048575 non-null  object
 20  ICU                 192543 non-null   object
dtypes: Int64(1), object(20)
memory usage: 169.0+ MB

In [58]:
# df['HastaTuru'] = df['HastaTuru'].pd.to_numeric(df['HastaTuru'], errors='coerce').astype('Int64')
# df['Yas'] = df['Yas'].pd.to_numeric(df['Yas'], errors='coerce').astype('Int64')
# df['CovidSiniflandirma'] = df['CovidSiniflandirma'].pd.to_numeric(df['CovidSiniflandirma'], errors='coerce').astype('Int64')

# 'HastaTuru' sütununu string'ten int'e çevir
df['HastaTuru'] = pd.to_numeric(df['HastaTuru'], errors='coerce').astype('Int64')

# 'Yas' sütununu string'ten int'e çevir
df['Yas'] = pd.to_numeric(df['Yas'], errors='coerce').astype('Int64')

# 'CovidSiniflandirma' sütununu string'ten int'e çevir
df['CovidSiniflandirma'] = pd.to_numeric(df['CovidSiniflandirma'], errors='coerce').astype('Int64')

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   TedaviDurumu        1048575 non-null  object
 1   TibbiBirim          1048575 non-null  object
 2   Cinsiyet            1048575 non-null  object
 3   HastaTuru           1048575 non-null  Int64
 4   SaglikDurumu        1048575 non-null  object
 5   Entube              192706 non-null   object
 6   Zaturre             1032572 non-null  object
 7   Yas                 1048354 non-null  Int64
 8   Hamile              525064 non-null   object
 9   Diyabet             1048575 non-null  Int64
 10  KOAH                1048575 non-null  object
 11  Astim               1048575 non-null  object
 12  BagisiklikSistemi   1048575 non-null  object
 13  HiperTansiyon       1048575 non-null  object
 14  DigerHastalik       1048575 non-null  object
 15  Kardiyovaskuler     1048575 non-null  object
 16  Obezite             1048575 non-null  object
 17  KronikBobrek        1048575 non-null  object
 18  Sigara              1048575 non-null  object
 19  CovidSiniflandirma  1048575 non-null  Int64
 20  ICU                 192543 non-null   object
dtypes: Int64(4), object(17)
memory usage: 172.0+ MB

In [61]:
# DataFrame'i CSV dosyasına kaydet
df.to_csv('duzenlenmis_Covid19.csv.csv', index=False)